logging:
  level:
    ROOT: debug
    org:
      springframework:
        data:
          mongodb:
            core: info
  config: classpath:logback-dev.xml
  file:
    path: logs/datart-core.log

spring:
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 64
        keep-alive: 120s
      thread-name-prefix: core-
