apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-spark-history
  namespace: spark
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi