image:
  repository: spark/livy-spark
  tag: 0.8.0-incubating-spark_3.2.1_2.12-hadoop_3.2.0_cloud
  pullPolicy: IfNotPresent

#nodeSelector:
#  node: service

service:
  type: LoadBalancer
  # nodePort: 32000
  port:
    number: 18080
    name: http-historyport

environment:
# Note: do not configure Spark history events directory using SPARK_HISTORY_OPTS. It will be
# configured by this chart based on the values in "pvc", "gcs" or "hdfs" attribute.
  SPARK_HISTORY_OPTS: "-Dspark.history.fs.cleaner.enabled=true -Dspark.history.fs.logDirectory=s3a://spark/eventLog -Dspark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem -Dspark.hadoop.fs.s3a.endpoint=http://minio.storage.svc:9000 -Dspark.hadoop.fs.s3a.access.key=a3e7d88d4fa8 -Dspark.hadoop.fs.s3a.secret.key=8b622eb12ff7"
  SPARK_DAEMON_MEMORY: 4G
  # SPARK_DAEMON_JAVA_OPTS: ...
  # SPARK_DAEMON_CLASSPATH: ...
  # SPARK_PUBLIC_DNS: ...

pvc:
  # to use a file system path for Spark events dir, set 'enablePVC' to true and mention the
  # name of an already created persistent volume claim in existingClaimName.
  # The volume will be mounted on /data in the pod
  enablePVC: false
  existingClaimName: pvc-spark-history
  eventsDir: "eventLog"

# Settings for the sub-chart
# When pvc.enablePVC is true, make sure:
# pvc.existingClaimName == nfs.pvcName
nfs:
  enableExampleNFS: false
  pvName: nfs-pv
  pvcName: nfs-pvc

s3:
  enableS3: true
  enableIAM: false
  # Omit for IAM role-based or provider-based authentication.
  secret: aws-secrets
  # accessKeyName is an AWS access key ID. Omit for IAM role-based or provider-based authentication.
  accessKeyName: aws-access-key
  # secretKey is AWS secret key. Omit for IAM role-based or provider-based authentication.
  secretKeyName: aws-secret-key
  logDirectory: "s3a://spark/eventLog"
  # custom s3 endpoint. Keep default for using aws s3 endpoint
  endpoint: http://minio.storage.svc:9000

#ingress:
#  enabled: true
#  annotations:
#   kubernetes.io/ingress.class: nginx
#   nginx.ingress.kubernetes.io/secure-backends: "false"
#   nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
#  path: /
#  hosts:
#    - spark-history-server.matrix.local
