# -- Set this if running spark jobs in a different namespace than the operator
sparkJobNamespace: "spark"

ingressUrlFormat: "spark.matrix.local/{{$appNamespace}}/{{$appName}}"

webhook:
  # -- Enable webhook server
  enable: true

